name: Build GamepadCore

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: false

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libasound2-dev libudev-dev libsdl2-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_TESTS=OFF -DAUTOMATED_TESTS=ON -DGAMEPAD_CORE_ENABLE_AUDIO=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target GamepadCore
